### PR TITLE
feat: add 6-sided format to skybox import/export

### PR DESCRIPTION
**Pull request by ngsp94**
ED-1224

After this is merged in, I'll have to update the submodule commits in 'io.area28.unity' and 'unity-viewer'.

### CODE REVIEW

**Comment by ngsp94** [comment]
If you'd like to test, you'd have to create a 6-sided skybox material for export.

These textures would probably be useful: https://opengameart.org/art-search?keys=cubemap

**Comment by donutboyy** [comment]
When I try importing a glb/gltf file, the skybox has a missing material. Am I missing something?
image

**Comment by ngsp94** [comment]
> When I try importing a glb/gltf file, the skybox has a missing material. Am I missing something? image

Is your import project also using this version of glTFast? I've put both export and import changes in this branch.

**Comment by donutboyy** [comment]
> Is your import project also using this version of glTFast? I've put both export and import changes in this branch.

yes i've just created a new scene within the same project to test

**Comment by ngsp94** [comment]
For me I used the Unity viewer project. You can add this entry to the `manifest.json` dependencies.

```
"com.atteneder.gltfast": "https://github.com/area28technologies/glTFast.git#b2f9bd52390b9068e87a87e0fd6dcf9963755627f",
```

**Comment by ngsp94** [comment]
> > Is your import project also using this version of glTFast? I've put both export and import changes in this branch.
> 
> yes i've just created a new scene within the same project to test

Strange. Let me try that.

**Comment by ngsp94** [comment]
It works for me. A few things to check:

- If there are missing shader errors, it's the old problem with embedding the glTFast package in the Area28 package
- Did you assign the skybox material in the rendering settings and save the scene before export?
- You can try exporting to `.gltf`, then search the file for 'skybox'. If it doesn't exist, then even the export set-up has issues.

**Review by donutboyy — APPROVED** [review]
Works well at runtime 👍 , I was importing the GLTF files in the editor which is what causes the issues above. Should be ok for now since we unity-viewer loads the scene at runtime anyway. Thanks for the help 🙏

**Review by vayan — APPROVED** [review]
All good for me too!

**Pull request merged**
